import Head from 'next/head'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import TournamentList from '@/components/TournamentList'
import { TournamentFormProps } from '../types/form-types'; // Adjust the path based on your project structure
import TournamentForm from '@/components/CreateTournament';

export default function SignIn() {
  const session = useSession()
  const supabase = useSupabaseClient()

  const handleFormSubmit: TournamentFormProps['onSubmit'] = (formData) => {
    // Handle the form data (e.g., send it to an API, save it to state, etc.)
    console.log(formData);
  };

  return (
    <>
        <Head>
            <title>Beerpongly</title>
            <meta name="description" content="Generated by Beerpongly" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="min-w-full min-h-screen flex items-center justify-center">
        <div className="w-full h-full flex justify-center items-center p-4">
            <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                <span className="font-sans text-4xl text-center pb-2 mb-1 border-b mx-4 align-center">
                    Login
                </span>
                <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />
            </div>
        </div>
        </div>
    </>
  )
}
